<#
.SYNOPSIS
    Deploy Azure infrastructure for FD Rate Scraper and configure .env file.

.DESCRIPTION
    Deploys Storage Account + AI Services to the specified resource group,
    then writes connection values into ../.env so the backend can run locally.

.PARAMETER ResourceGroup
    Name of the Azure resource group (will be created if it doesn't exist).

.PARAMETER Location
    Azure region. Default: eastus2
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$ResourceGroup,

    [string]$Location = "eastus2"
)

$ErrorActionPreference = "Stop"

Write-Host "`n=== FD Rate Scraper — Azure Setup ===" -ForegroundColor Cyan

# 1. Ensure logged in
Write-Host "`n[1/5] Checking Azure CLI login..." -ForegroundColor Yellow
$account = az account show 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Host "Not logged in. Running az login..." -ForegroundColor Yellow
    az login
}
Write-Host "  Logged in as: $($account.user.name)" -ForegroundColor Green

# 2. Create resource group if needed
Write-Host "`n[2/5] Ensuring resource group '$ResourceGroup' in '$Location'..." -ForegroundColor Yellow
az group create --name $ResourceGroup --location $Location --output none 2>$null
Write-Host "  Resource group ready." -ForegroundColor Green

# 3. Deploy Bicep
Write-Host "`n[3/5] Deploying Bicep template..." -ForegroundColor Yellow
$deployment = az deployment group create `
    --resource-group $ResourceGroup `
    --template-file "$PSScriptRoot\main.bicep" `
    --output json | ConvertFrom-Json

$outputs = $deployment.properties.outputs
$storageConn    = $outputs.storageConnectionString.value
$aiEndpoint     = $outputs.aiServicesEndpoint.value
$storageName    = $outputs.storageAccountName.value
$aiName         = $outputs.aiServicesName.value

Write-Host "  Deployment succeeded." -ForegroundColor Green
Write-Host "    Storage Account : $storageName"
Write-Host "    AI Services     : $aiName"
Write-Host "    AI Endpoint     : $aiEndpoint"

# 4. Write .env
Write-Host "`n[4/5] Writing .env file..." -ForegroundColor Yellow
$envPath = Join-Path $PSScriptRoot "..\.env"
@"
# Auto-generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
FOUNDRY_PROJECT_ENDPOINT=$aiEndpoint
FOUNDRY_MODEL_DEPLOYMENT_NAME=gpt-4o
AZURE_STORAGE_CONNECTION_STRING=$storageConn
AZURE_STORAGE_CONTAINER_NAME=fd-rates
BACKEND_PORT=8000
CORS_ORIGINS=http://localhost:3000
"@ | Set-Content -Path $envPath -Encoding UTF8
Write-Host "  .env written to $envPath" -ForegroundColor Green

# 5. Summary
Write-Host "`n[5/5] Setup complete!" -ForegroundColor Cyan
Write-Host @"

Next steps:
  1. cd backend && pip install -r requirements.txt
  2. uvicorn backend.main:app --reload --port 8000
  3. cd frontend && npm install && npm start
  4. Open http://localhost:3000 in your browser
"@ -ForegroundColor White
